version: '3.8'

services:
  # Strapi Backend
  strapi:
    build: ./backend
    container_name: strapi-renda-de-file
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      JWT_SECRET: your-jwt-secret-here
      ADMIN_JWT_SECRET: your-admin-jwt-secret-here
      APP_KEYS: your-app-keys-here
      API_TOKEN_SALT: your-api-token-salt-here
      TRANSFER_TOKEN_SALT: your-transfer-token-salt-here
    volumes:
      - ./backend/config:/app/config
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
      - ./backend/public/uploads:/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres-renda-de-file
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - strapi

  # Next.js Frontend (for development)
  frontend:
    build: ./frontend
    container_name: frontend-renda-de-file
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_STRAPI_URL: http://localhost:1337
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: your-google-maps-api-key
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    networks:
      - strapi
    depends_on:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
