import type { StrapiApp } from '@strapi/strapi/admin';

export default {
  config: {
    locales: ['pt-BR'],
    translations: {
      'pt-BR': {
        'content-manager.components.FieldItem.linkToComponentLayout': 'Configurar o layout do componente',
        'content-manager.containers.Edit.pluginHeader.title.new': 'Criar entrada',
        'content-manager.containers.Edit.pluginHeader.title.edit': 'Editar entrada',
        'content-manager.containers.ListPage.displayedFields': 'Campos exibidos',
        'content-manager.containers.ListPage.table.headers.publishedAt': 'Publicado em',
        'content-manager.containers.ListPage.table.headers.updatedAt': 'Atualizado em',
        'content-manager.containers.ListPage.table.headers.createdAt': 'Criado em',
        'content-manager.containers.SettingsPage.Block.contentType.title': 'Tipos de conteúdo',
        'content-manager.containers.SettingsPage.Block.component.title': 'Componentes',
        'content-manager.containers.SettingsPage.pluginHeaderDescription': 'Configure como o conteúdo é exibido',
        'content-manager.containers.SettingsPage.pluginHeaderTitle': 'Configurações - Gerenciador de Conteúdo',
        'content-manager.form.Input.bulkActions': 'Ações em lote',
        'content-manager.form.Input.filters': 'Filtros',
        'content-manager.form.Input.search': 'Buscar',
        'content-manager.form.Input.sort': 'Ordenar',
        'content-manager.global.displayedFields': 'Campos exibidos',
        'content-manager.notification.success.delete': 'Item excluído',
        'content-manager.notification.success.publish': 'Item publicado',
        'content-manager.notification.success.unpublish': 'Item despublicado',
        'content-manager.notification.success.saved': 'Salvo',
        'content-manager.popUpWarning.bodyMessage.contentType.delete': 'Tem certeza de que deseja excluir esta entrada?',
        'content-manager.popUpWarning.warning.publish': 'Tem certeza de que deseja publicar?',
        'content-manager.popUpWarning.warning.unpublish': 'Tem certeza de que deseja despublicar?',
        'content-manager.success.record.delete': 'Excluído',
        'content-manager.success.record.publish': 'Publicado',
        'content-manager.success.record.save': 'Salvo',
        'content-manager.success.record.unpublish': 'Despublicado',
        'content-manager.utils.error.model.fetch': 'Erro ao buscar dados',
        'content-manager.utils.error.model.save': 'Erro ao salvar',
        'content-manager.utils.error.model.delete': 'Erro ao excluir',
        'content-manager.utils.error.model.publish': 'Erro ao publicar',
        'content-manager.utils.error.model.unpublish': 'Erro ao despublicar',
        'Settings': 'Configurações',
        'Content Manager': 'Gerenciador de Conteúdo',
        'Media Library': 'Biblioteca de Mídia',
        'Users & Permissions plugin': 'Plugin de Usuários e Permissões',
        'Roles': 'Funções',
        'Users': 'Usuários',
        'Providers': 'Provedores',
        'Email templates': 'Modelos de email',
        'Advanced settings': 'Configurações avançadas',
        'API Tokens': 'Tokens da API',
        'Transfer Tokens': 'Tokens de Transferência',
        'Webhooks': 'Webhooks',
        'Internationalization': 'Internacionalização',
        'Locales': 'Idiomas',
        'Upload': 'Upload',
        'Upload settings': 'Configurações de upload',
        'Global settings': 'Configurações globais',
        'Administration Panel': 'Painel de Administração',
        'Welcome': 'Bem-vindo',
        'app.components.HomePage.welcome': 'Bem-vindo ao Strapi!',
        'app.components.HomePage.welcome.again': 'Bem-vindo de volta!',
        'app.components.LeftMenu.navbrand.title': 'Painel Strapi',
        'app.components.LeftMenu.navbrand.workplace': 'Área de trabalho',
        'app.components.NotFoundPage.back': 'Voltar à página inicial',
        'app.components.NotFoundPage.description': 'Oops! A página que você está procurando não foi encontrada.',
        'app.components.NotFoundPage.title': 'Página não encontrada',
        'app.utils.defaultMessage': 'Mensagem padrão',
        'Auth.form.button.forgot-password': 'Enviar email',
        'Auth.form.button.go-home': 'VOLTAR AO INÍCIO',
        'Auth.form.button.login': 'Entrar',
        'Auth.form.button.register': 'Vamos começar!',
        'Auth.form.button.reset-password': 'Alterar senha',
        'Auth.form.confirmPassword.label': 'Confirmar senha',
        'Auth.form.confirmPassword.placeholder': 'Confirme sua senha',
        'Auth.form.currentPassword.label': 'Senha atual',
        'Auth.form.currentPassword.placeholder': 'Digite sua senha atual',
        'Auth.form.email.label': 'Email',
        'Auth.form.email.placeholder': 'Digite seu email',
        'Auth.form.firstname.label': 'Nome',
        'Auth.form.firstname.placeholder': 'Digite seu nome',
        'Auth.form.lastname.label': 'Sobrenome',
        'Auth.form.lastname.placeholder': 'Digite seu sobrenome',
        'Auth.form.password.label': 'Senha',
        'Auth.form.password.placeholder': 'Digite sua senha',
        'Auth.form.rememberMe.label': 'Lembrar de mim',
        'Auth.form.username.label': 'Nome de usuário',
        'Auth.form.username.placeholder': 'Digite seu nome de usuário',
        'Auth.link.forgot-password': 'Esqueceu sua senha?',
        'Auth.link.ready': 'Pronto para entrar?',
        'Auth.link.signin': 'Entrar',
        'Auth.link.signin.account': 'Já tem uma conta?',
        'global.actions': 'Ações',
        'global.add': 'Adicionar',
        'global.back': 'Voltar',
        'global.cancel': 'Cancelar',
        'global.change-password': 'Alterar senha',
        'global.close': 'Fechar',
        'global.continue': 'Continuar',
        'global.delete': 'Excluir',
        'global.description': 'Descrição',
        'global.details': 'Detalhes',
        'global.disabled': 'Desabilitado',
        'global.edit': 'Editar',
        'global.email': 'Email',
        'global.enabled': 'Habilitado',
        'global.finish': 'Finalizar',
        'global.name': 'Nome',
        'global.none': 'Nenhum',
        'global.password': 'Senha',
        'global.reset': 'Redefinir',
        'global.save': 'Salvar',
        'global.search': 'Buscar',
        'global.see-more': 'Ver mais',
        'global.submit': 'Enviar',
        'global.type': 'Tipo',
        'global.update': 'Atualizar',
        'global.upload': 'Upload',
        'global.users': 'Usuários',
        'global.yes': 'Sim',
        'global.no': 'Não',
        'notification.error': 'Erro',
        'notification.success': 'Sucesso',
        'notification.warning': 'Aviso',
        'notification.info': 'Informação',
        'request.error.model.unknown': 'Erro desconhecido',
        'Skip to content': 'Pular para o conteúdo',
        'Submit': 'Enviar',
        'Cancel': 'Cancelar'
      }
    }
  },
  bootstrap(app: StrapiApp) {
    // Customizações adicionais podem ser adicionadas aqui
    console.log('🎨 Strapi Admin customizado carregado com traduções em português');
  },
};
